In [1]:
import torch

In [5]:
a = torch.arange(25).reshape(5,5)
print(a)
b = torch.abs(a)
print(b)
print(b.max(dim=0).values)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])
tensor([20, 21, 22, 23, 24])
