In [1]:
import torch

In [2]:
a = torch.arange(30).reshape((10,3))
a.sum(axis=0)

tensor([135, 145, 155])

In [8]:
x = torch.arange(3*4).reshape(3,4)
p = 0.1
mask = (torch.rand(*x.shape, device=x.device) > p) / p # scaling
print(x)
print(mask)
print(x * mask)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10.,  0., 10., 10.]])
tensor([[  0.,  10.,  20.,  30.],
        [ 40.,  50.,  60.,  70.],
        [ 80.,   0., 100., 110.]])


In [13]:
from fully_connected_networks import Dropout, Linear_ReLU

In [16]:
Dropout.__name__, Linear_ReLU.__name__

('Dropout', 'Linear_ReLU')

In [17]:
Dropout.__name__ == "Dropout"

True

In [3]:
torch.sum(a * a)

tensor(8555)